# Day 4 Exercises
## Object Oriented Programming

#### 1. Create a class called `Book` that has the attributes title, author, pages, price. It also has the method get_price() which returns price, and set_price() to ensure price is numeric.

Then create two instances of this class:

b1:
* title -> 'Practical Programming'
* author -> 'Gries, Campbell, Montojo'
* pages -> 383
* price -> 50

b2:
* title -> 'Building a Career in Data Science'
* author -> 'Robinson, Nolis'
* pages -> 322
* price -> 40

In [3]:
# Your code goes here
class Book:
    def __init__(self, title, author, pages, price):
        self.title = title
        self.author = author
        self.pages = pages
        self.price = price
    def get_price(self):
        return self.price
    def set_price(self, price):
        if len(price) > 0:
            self.price = price
        else:
            self.price = 0

b1 = Book('Practical Programming', 'Gries, Campbell, Montojo', 383, 50)
b2 = Book('Building a Career in Data Science', 'Robinson, Nolis', 322, 40)

#### 2. Create a `Phone` class that has the attributes model, id, name, brand and price. Create the getters and setters for each attribute. As well as the following methods: calculate_total which takes the price and calculates it by the tax argument.

In [7]:
class Phone:
    def __init__(self, model, id, name, brand, price):
        self.model = model
        self.id = id
        self.name = name
        self.brand = brand
        self.price = price
    def get_model(self):
        return self.model

    def set_model(self, model):
        self.model = model

    def get_id(self):
        return self.id

    def set_id(self, id):
        self.id = id

    def get_name(self):
        return self.name

    def set_name(self, name):
        self.name = name

    def get_brand(self):
        return self.brand

    def set_brand(self, brand):
        self.brand = brand

    def get_price(self):
        return self.price

    def set_price(self, price):
        self.price = price

    def calculate_total(self, tax):
        return self.price * (1 + tax)




## Numpy

In [8]:
import numpy as np

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

Original Array: [0 1 2 3 4 5]

Reshaped 2x3 Array:

[[0 1 2]

[3 4 5]]

In [9]:
vector = np.array([0, 1, 2, 3, 4, 5])
vector.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

#### 2. Create a 3×3 NumPy array of all True

*Hint! Use np.ones() with dtype=bool.*

In [10]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 3. Create a 1D array filled with zeros and another filled with ones

In [13]:
np.zeros((3))

np.ones((3))

array([1., 1., 1.])

#### 4. Reverse a 1D NumPy array
Ex. arr = np.arange(10)

Output is [9 8 7 6 5 4 3 2 1 0]

*Hint! Use slicing with step = -1.*

In [23]:
arr = np.arange(10)
arr
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 5. Stack these arrays horizontally


a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

#### 6. Perform arithmetic operations on two NumPy arrays element-wise

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

*   Add two NumPy arrays element by element.
*   Multiply two NumPy arrays element by element.

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b
a * b

array([ 4, 10, 18])